### ISSUE TITLE
Not Found?

### ISSUE THREAD

**Issue by e-roy** [novum-insights/unlock-protocol-firebase#6]
Hello,  I tried to install the npm package and got the error:

```
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@novum%2funlock-firebase-integration - Not found
npm ERR! 404
npm ERR! 404  '@novum/unlock-firebase-integration@*' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

Just wanted to check if this is an error on my part or no longer active

Thanks

**Comment by dmlayton** [comment]
I just did `npm install @novuminsights/unlock-protocol-firebase` without any issue. How did you attempt to install it?

Whoops! I see it said `@novum/unlock-firebase-integration` in the readme. I've fixed that!

**Comment by e-roy** [comment]
Awesome, that works!  Thank you

**Comment by e-roy** [comment]
@dmlayton I also saw it on your docs FYI
https://david-layton.gitbook.io/novum/
